// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_trev3law.Models;

namespace Mission06_trev3law.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_trev3law.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Action",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Lent_To = "Josh",
                            Notes = "Great Movie",
                            Rating = "PG-13",
                            Title = "The Dark Knight",
                            Year = 2013
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Rom/Com",
                            Director = "Some Guy",
                            Edited = false,
                            Lent_To = "Ashley",
                            Notes = "Funny Movie",
                            Rating = "PG-13",
                            Title = "Crazy Stupid Love",
                            Year = 2013
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Action",
                            Director = "Tom Cruise",
                            Edited = false,
                            Lent_To = "Me",
                            Notes = "The Best Movie",
                            Rating = "PG-13",
                            Title = "Top Gun Maverick",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
